@URL=http://localhost:3000/api
@JSON=Content-Type: application/json

# 
GET {{URL}}/hello HTTP/1.1



###
POST {{URL}}/register HTTP/1.1
{{JSON}}

{
	"username":"bob_here",
	"name":"Bob",
	"password":"bob_here",
	"email":"ye@test.com"
}
